In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.1'

In [9]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [11]:
b = np.array((6, 7, 8))
b

array([6, 7, 8])

In [12]:
type(a), type(b)

(numpy.ndarray, numpy.ndarray)

In [13]:
np.array(1, 2, 3)

ValueError: only 2 non-keyword arguments accepted

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [25]:
np.arange(1, 4, 0.5, dtype='float64')

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [34]:
np.linspace(2, 10, num=4, endpoint=False, retstep=True)

(array([2., 4., 6., 8.]), 2.0)

In [40]:
darray = np.array([[1, 2, 3], [4, 5, 6]])
print(darray)
darray.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [43]:
barray = np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]]])

print(barray)

barray.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


(2, 4, 3)

In [44]:
barray.ndim

3

In [51]:
azero = np.zeros([1, 2])
azero

array([[0., 0.]])

In [50]:
aones = np.ones((1, 2))
aones

array([[1., 1.]])